version: '2.4'
services:
  shellgame:
    build: .
    ports:
      - 11451:11451
    read_only: true
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
      - mknod
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined