version: "3"
services:
# local proxy credentials hxp:hxp
  bot:
    build:
      dockerfile: Dockerfile-admin
    restart: always
    depends_on:
      - chall
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    ports:
      - 9762:1024

  chall:
    build:
      dockerfile: Dockerfile

    restart: always
    ports:
      - 9032:8091
